<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11"/>
        <PackageReference Include="AWSSDK.S3" Version="4.0.102.4"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Files.Application\Files.Application.csproj"/>
    </ItemGroup>
</Project>
